name = "athena"
compatibility_date = "2024-01-01"

[site]
bucket = ".svelte-kit/cloudflare"

# Environment variables
# In production, set these in Cloudflare dashboard
# [env.production.vars]
# DISCORD_CLIENT_ID = "your-discord-client-id"
# DISCORD_CLIENT_SECRET = "your-discord-client-secret"
# DISCORD_REDIRECT_URI = "https://your-domain.pages.dev/api/auth/callback"
